### PR TITLE
Sync with the new version 

### PR DESCRIPTION
**Pull request by ypriverol**
@hbarsnes would be good if both versions are sync.

### CODE REVIEW

**Comment by hbarsnes** [comment]
@ypriverol Why would we update the old version of the OLS Dialog? It has been deprecated and replaced by the new version as indicated on the front page: "The OLS Dialog project is now maintained at https://github.com/PRIDE-Toolsuite/ols-dialog. The version at this page is deprecated and will not work with the updated version of the OLS."

**Comment by ypriverol** [comment]
@hbarsnes i think is good to keep this version also updated at least with a working "non-updated version" because if someone found this version by chance would be good that at least it works with the new ols, but is up to you

**Comment by hbarsnes** [comment]
@ypriverol I would prefer deprecating it instead. Same as we did for the original PRIDE Converter. Having two updated version (or rather one updated and one semi-updated) is more confusing I think?

**Comment by ypriverol** [comment]
Transfer this repo to PRIDE Toolsuite and merge the current fork into the main branch and keep only one repo on the entire github?

**Comment by hbarsnes** [comment]
> Transfer this repo to PRIDE Toolsuite and merge the current fork into the main branch and keep only one repo on the entire github?

That could be an option. My main point is to not have to maintain two versions when one of them really is deprecated and should not be used.

**Pull request merged**
